@CartAPI_HostAddress = http://localhost:5141

### Login (el token se reutiliza abajo)
# @name login
POST {{CartAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "cliente@cartapi.local",
  "password": "Cliente123!"
}

###
@token = {{login.response.body.accessToken}}

### Usuario autenticado
GET {{CartAPI_HostAddress}}/api/auth/me
Authorization: Bearer {{token}}

### Sin token -> 401
GET {{CartAPI_HostAddress}}/api/auth/me





### Products
GET {{CartAPI_HostAddress}}/api/products
Authorization: Bearer {{token}}

### Search products
GET {{CartAPI_HostAddress}}/api/products?search=Cafetera de goteo
Authorization: Bearer {{token}}

### Get product by id
GET {{CartAPI_HostAddress}}/api/products/3
Authorization: Bearer {{token}}




### Categories
GET {{CartAPI_HostAddress}}/api/categories
Authorization: Bearer {{token}}





### Cart
GET {{CartAPI_HostAddress}}/api/cart
Authorization: Bearer {{token}}


### Add item to cart
POST {{CartAPI_HostAddress}}/api/cart/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productId": 2,
  "quantity": 1
}


### Set item quantity in cart
PUT {{CartAPI_HostAddress}}/api/cart/items/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "quantity": 6
}


### Remove item from cart
DELETE {{CartAPI_HostAddress}}/api/cart/items/2
Authorization: Bearer {{token}}


### Clear cart
DELETE {{CartAPI_HostAddress}}/api/cart
Authorization: Bearer {{token}}


